### ISSUE TITLE
Why page reloads?

### ISSUE THREAD

**Issue by 12gsdi** [sveltetools/svelte-pathfinder#37]
Do I completely misunderstand the intention of routers? Why is your router reloading the pages? Isn't the purpose of a router in an SPA suppose to NOT reload the page???? How is state to persist with this design?

**Comment by 12gsdi** [comment]
If someone is searching for a svelte router it's because they don't want to use Sveltekit....which reloads the page????? So confused

**Comment by PaulMaly** [comment]
Hi! Maybe I completely misunderstand your issue, but this router don’t reload pages, because uses History API under the hood. Of course, if you use it as expected. Actually, pathfinder completely unopinionated how exactly you’ll use it in your application and provides only very low-level but in the same time very powerful  instruments to manipulating with routing state. That’s why, to help you with your problems I need to have an example of how you exact use it. Let’s try to find out why it not working as you expected together.


Btw. SvelteKit doesn’t reload the pages as well. It uses universal (isomorphic) approaches to build the apps, combining both - server and client - sides to provide better performance and UX.

**Comment by PaulMaly** [comment]
First of all, please make sure that you’re handle clicks on all your navigation links and preventDefault on its behavior. Alternatively, you can use `click` helper from pathfinder on window object to handle click of all regular <a> tags in your app:

`<svelte:window on:click={click} />`

**Comment by PaulMaly** [comment]
@12gsdi Are you solved your issue? Any additional questions?

**Comment by PaulMaly** [comment]
Closed for now because of inactivity. Feel free to reopen any time you needed.
